---
- name: git clone application
  git: repo={{ git_url }}
       dest={{ home }}/{{ app_name }}
       version={{ git_branch }}
- name: create shared directory
  shell: mkdir -p {{ home }}/{{ app_name }}_shared
- name: create shared socket directory
  shell: mkdir -p {{ home }}/{{ app_name }}_shared/sockets
- name: create shared log directory
  shell: mkdir -p {{ home }}/{{ app_name }}_shared/log
- name: create shared pids directory
  shell: mkdir -p {{ home }}/{{ app_name }}_shared/pids
- name: create Gemfile.lock
  file: path={{ home }}/{{ app_name }}/Gemfile.lock state=touch owner={{user}} group={{user}} mode=0644
